#!/usr/bin/env python3

### getting stats from a protein sequence provided in FASTA file ###
# need to get import stats on main script 
# calculate_stats already in main 

# input from main script after parse_fasta = sequences

import sys
from Bio import SeqIO

id_dict = SeqIO.to_dict_parse(SeqIO.parse((sys.argv[1]),'fasta'))
print (id_dict)

#def calculate_stats(sequences):
#	sequence_lengths = [len(seq) for seq in sequences.values()]
#	total_sequences = len(sequences)
#	max_length = max(sequence_lengths)
#	min_length = min(sequence_lengths)
#	avg_length = statistics.mean(sequence_lengths)
 
#	sorted_lengths = sorted(sequence_lengths)
#	n50 = 0
#	l50 = 0
#	half_total_length = sum(sequence_lengths) / 2
  
#	for length in sorted_lengths:
#		n50 += length
#		if n50 >= half_total_length:
#			l50 = length
#			break
	
#	M_count = {}
#	for aa in sequences:
#		if aa == 'M':
#			seq_ID = sequences.keys()
#			seq = sequences.values()
#			M_count(seq_ID) = seq.count(aa)
#	print(M_count)
